# Generated by Django 4.1.2 on 2022-10-15 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="message",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="phone_number",
            field=models.TextField(blank=True, null=True),
        ),
    ]
